### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Emantor** [kipe/python-onewire#4]
Hello,

to properly integrate the onewire library as a dependency into @labgrid-project, we would like a new version to depend on 👍 If you need any help working on features for an upcoming release just mention it, I can spare some company time to work on that.

**Comment by kipe** [comment]
Hey, awesome to hear that there's intrest and need for this project :)

Would really help if you could track down and fix issue #1, after this I don't see any reason not to do a release.

**Comment by Emantor** [comment]
Since I fixed Issue #1, could you release a new version so we can properly depend on it via Pypi?

**Comment by kipe** [comment]
Damn it, was supposed to but forgot!
I'll do it straight away :)

**Comment by kipe** [comment]
Done and released to PyPi, thanks for the fixes @Emantor :+1:
